theme: stack
baseURL: https://yellowzeyu.com
copyright: HUANG Zeyu (黄泽宇)

defaultContentLanguage: zh-cn
languages:
  zh-cn:
    languageName: 简体中文
    hasCJKLanguage: true
    title: 黄泽宇的个人网站
    copyright: 黄泽宇（HUANG Zeyu）
    # stack-theme comments
    comments:
      enabled: true
      provider: waline
      waline:
        serverURL: https://comments.yellowzeyu.com/
        lang: zh-CN
        emoji: false
        requiredMeta:
          - nick
          - mail
        wordLimit: [5, 300]
        turnstileKey: 0x4AAAAAAAEuM1PYiEo4yqeY
  en:
    languageName: English
    hasCJKLanguage: false
    title: HUANG Zeyu's Website
    # stack-theme comments
    comments:
      enabled: true
      provider: waline
      waline:
        serverURL: https://comments.yellowzeyu.com/
        lang: en
        emoji: false
        requiredMeta:
          - nick
          - mail
        wordLimit: [5, 300]
        turnstileKey: 0x4AAAAAAAEuM1PYiEo4yqeY

menu:
  social:
    - name: GitHub
      url: https://github.com/fhfuih
      params:
        icon: brand-github
        # newTab: false
    - name: LinkedIn
      url: https://www.linkedin.com/in/zeyu-huang-522a52178/
      params:
        icon: brand-linkedin
    - name: ORCiD
      url: https://orcid.org/0000-0001-8199-071X
      params:
        icon: orcid
    # params:
    #   icon: null

params:
  favicon: /favicon.ico
  mainSections:
    - blog
  sidebar:
    avatar:
      local: true
      src: avatar.jpg
  featuredImageField: featured_image
  citation_author: Huang, Zeyu
  # stack-theme comments
  comments:
    enabled: true
    provider: waline
    waline:
      serverURL: https://comments.yellowzeyu.com/
      lang: zh-CN
      # avatar:
      # emoji:
      #     - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
      requiredMeta:
        - name
        - email
        # - url
      # locale:
      #     admin: Admin

markup:
  goldmark:
    renderer:
      unsafe: true

# debug
enableMissingTranslationPlaceholders: true
